version: '3.9'
services:
  ui_app:
    container_name: ui_app
    build: ./groupyz
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./groupyz:/Frontend_app
    environment:
      - CHOKIDAR_USEPOLLING=true
