version: '3'
services: 
  frontend:
    restart: always
    build: ./groupyz
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./groupyz:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
